### PR TITLE
Upgrade stack to ruby 3.3, rack 3.0 and sinatra 4.0

### PR DESCRIPTION
**Pull request by jmoniatte**
Upgrade the ruby/rack/sinatra to their latest versions. Besides the various security patches, we are specifically interested in:

* Speed improvements we get from ruby 3.3 with YJIT
* Rack to [stop using semicolons as query params separator](https://github.com/rack/rack/pull/1733)

Validated that YJIT is enabled in the container:

```bash
ruby -v
ruby 3.3.3 (2024-06-12 revision f1c7b6f435) +YJIT [x86_64-linux]
```

@abealsaleh how do you recommend we test this? Local testing is limited because of the lack of geoip database and DEM files.

### CODE REVIEW

**Comment by abealsaleh** [comment]
we can build a container and deploy it to a test instance.

**Review by abealsaleh — APPROVED** [review]

**Comment by jmoniatte** [comment]
> we can build a container and deploy it to a test instance

Awesome. Is that something you can handle soonish?

**Comment by abealsaleh** [comment]
> > we can build a container and deploy it to a test instance
> 
> Awesome. Is that something you can handle soonish?

I can handle in the morning tomorrow

**Comment by jmoniatte** [comment]
[Developer QA pass](https://github.com/ridewithgps/ridewithgps/pull/16165) on the stack upgrade. Closing this PR, we will request a formal QA pass from the QA team on #38.

**Pull request closed without merging**
